//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzikSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeri
    {
        public int GaleriID { get; set; }
        public string GaleriResim { get; set; }
        public string ResimAcıklama { get; set; }
        public Nullable<bool> AktiflikDurumu { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
    }
}
