//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzikSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        public int iletisimID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Eposta { get; set; }
        public string Mesaj { get; set; }
        public string ipAdresi { get; set; }
    }
}
