//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzikSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int kullanici_id { get; set; }
        public string kullanici_Ad { get; set; }
        public string kullanici_Soyad { get; set; }
        public string kullanici_Mail { get; set; }
        public string kullanici_Sifre { get; set; }
        public string kullanici_Adi { get; set; }
        public string aktifMi { get; set; }
        public Nullable<int> kullaniciTuruID { get; set; }
    
        public virtual kullaniciTuru kullaniciTuru { get; set; }
    }
}
